name: Laravel CI

on:

  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug

      - name: Copying .env.example to .env
        run: |
          cd server/
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: |
          cd server/
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate the application key
        run: |
          cd server/
          php artisan key:generate

      - name: Directory Permissions
        run: |
          cd server/
          chmod -R 777 storage bootstrap/cache

      - name: Execute the tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          cd server/
          php artisan test --parallel

      # - name: Execute code style check
      #   run: |
      #     cd server/
      #     vendor/bin/pint --test

      - name: Execute Larastan code quality checking
        run: |
          cd server/
          vendor/bin/phpstan analyse